services:
  vue-app:
    image: node:20.13.0-alpine
    container_name: ${CONTAINER_NAME}
    working_dir: /app
    volumes:
      - ./vue-app:/app
    ports:
      - "8080:5173"
    command: sh -c "yarn install && yarn dev --host 0.0.0.0"