services:
  vue-app:
    image: node:22.13.1
    container_name: vue-app
    working_dir: /app
    volumes:
      - ./vue-app:/app
    ports:
      - "8080:5173"
    command: >
      bash -c "yarn install &&
      yarn dev --host 0.0.0.0"